# Generated by Django 5.1.7 on 2025-04-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('userEmail', models.EmailField(max_length=254, unique=True)),
                ('submited_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
