# Generated by Django 5.1.7 on 2025-04-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_newsletter_useremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('Comments', models.TextField()),
                ('Commented_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
