# Generated by Django 5.1.7 on 2025-04-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_rename_comments_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('descriptions', models.TextField()),
                ('selling_price', models.PositiveIntegerField()),
                ('quantity', models.PositiveBigIntegerField()),
                ('total_price', models.PositiveBigIntegerField()),
                ('country', models.CharField(max_length=200)),
                ('ordered_By', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('address2', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('orderNote', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
