# Generated by Django 5.1.7 on 2025-04-04 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_oder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oder',
            new_name='Order',
        ),
    ]
