# Generated by Django 5.1.7 on 2025-04-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_rename_oder_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(),
        ),
    ]
