# Generated by Django 5.1.7 on 2025-04-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_images',
            field=models.ImageField(default='exit', upload_to='OrderMedia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, null=True),
        ),
    ]
