# Generated by Django 5.1.7 on 2025-04-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_images', models.ImageField(upload_to='OrderMedia')),
                ('descriptions', models.TextField()),
                ('selling_price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=200)),
                ('ordered_By', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('address2', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('orderNote', models.TextField(blank=True, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
