# Generated by Django 5.1.7 on 2025-04-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_paidorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paidorder',
            old_name='order_date',
            new_name='completed_at',
        ),
        migrations.RenameField(
            model_name='paidorder',
            old_name='ordered_By',
            new_name='customer_name',
        ),
        migrations.RemoveField(
            model_name='paidorder',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='paidorder',
            name='country',
        ),
        migrations.RemoveField(
            model_name='paidorder',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='paidorder',
            name='emailAddress',
        ),
        migrations.RemoveField(
            model_name='paidorder',
            name='orderNote',
        ),
        migrations.RemoveField(
            model_name='paidorder',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='paidorder',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='paidorder',
            name='state',
        ),
    ]
