# Generated by Django 5.1.7 on 2025-04-09 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_rename_order_date_paidorder_completed_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paidorder',
            old_name='customer_name',
            new_name='ordered_By',
        ),
    ]
