# Generated by Django 5.1.7 on 2025-04-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_blog_blogimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_images',
            field=models.ImageField(default='date', upload_to='Blogimages'),
            preserve_default=False,
        ),
    ]
