# Generated by Django 5.1.7 on 2025-04-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_blog_blog_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='category_title',
            field=models.CharField(help_text='Remove Image Background for better look.**', max_length=200, unique=True),
        ),
    ]
