# Generated by Django 5.1.7 on 2025-04-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_about_alter_category_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_images',
            field=models.ImageField(help_text='Remove Image Background for better look.**', upload_to='Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
