# Generated by Django 5.1.7 on 2025-04-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_order_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidorder',
            name='status',
            field=models.CharField(default='completed', max_length=50),
            preserve_default=False,
        ),
    ]
