# Generated by Django 5.1.7 on 2025-04-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_paidorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paidorder',
            name='phone_number',
            field=models.IntegerField(default='12345'),
            preserve_default=False,
        ),
    ]
